#!/bin/bash

Rscript ./create_environment_scripts/install_packages.R

pip3 install virtualenv
python3 -m venv ./virtualenv
source ./virtualenv/bin/activate
./virtualenv/bin/pip3 install -r ./create_environment_scripts/requirements.txt 

./virtualenv/bin/pip3 install jupyterlab
